Repository kartoza/freshwaterbiodiversity.org, pull requests merged in 2018-03, with the labels that each got.

#95 Base models for fish
  deployment/docker/REQUIREMENTS.txt
  django_project/base/admin.py
  django_project/base/forms/__init__.py
  django_project/base/migrations/0001_initial.py
  django_project/base/migrations/__init__.py
  django_project/base/models/__init__.py
  django_project/base/models/location_site.py
  django_project/base/models/location_type.py
  django_project/base/templates/landing_page.html
  django_project/base/test/__init__.py
  django_project/base/test/model_factories.py
  django_project/base/test/test_models.py
  django_project/core/base_static/css/base.css
  django_project/core/base_templates/main_base.html
  django_project/core/settings/base.py
  django_project/core/settings/project.py
  django_project/core/test/__init__.py
  django_project/core/test/model_factories.py
  django_project/core/urls.py
  django_project/fish/__init__.py
  django_project/fish/admin.py
  django_project/fish/forms/__init__.py
  django_project/fish/forms/csv_upload.py
  django_project/fish/migrations/0001_initial.py
  django_project/fish/migrations/0002_auto_20180312_0428.py
  django_project/fish/migrations/0003_auto_20180312_0512.py
  django_project/fish/migrations/0004_auto_20180312_0541.py
  django_project/fish/migrations/0005_auto_20180312_0541.py
  django_project/fish/migrations/__init__.py
  django_project/fish/models/__init__.py
  django_project/fish/models/csv_document.py
  django_project/fish/models/fish_collection_record.py
  django_project/fish/models/iucn_status.py
  django_project/fish/models/taxon.py
  django_project/fish/static/csv_uploader.css
  django_project/fish/templates/csv_uploader.html
  django_project/fish/test/__init__.py
  django_project/fish/test/model_factories.py
  django_project/fish/test/test_models.py
  django_project/fish/urls.py
  django_project/fish/views/__init__.py
  django_project/fish/views/csv_upload.py
Labels: needsreview

#104 Install grappelli for admin page
  deployment/docker/REQUIREMENTS.txt
  django_project/core/settings/contrib.py
  django_project/core/urls.py
Labels: in progress

#105 Add api
  deployment/Makefile
  deployment/docker-compose.yml
  deployment/docker/REQUIREMENTS.txt
  django_project/base/urls.py
  django_project/core/settings/contrib.py
  django_project/core/urls.py
  django_project/fish/admin.py
  django_project/fish/api_views/__init__.py
  django_project/fish/api_views/fish_collection_record.py
  django_project/fish/api_views/taxon.py
  django_project/fish/migrations/0006_auto_20180313_0355.py
  django_project/fish/serializers/__init__.py
  django_project/fish/serializers/fish_collection_serializer.py
  django_project/fish/serializers/taxon_serializer.py
  django_project/fish/urls.py
Labels: in progress

#96 extend user and migrate old data
  .gitignore
  deployment/Makefile
  deployment/docker-compose.yml
  django_project/base_user/__init__.py
  django_project/base_user/migrations/0001_initial.py
  django_project/base_user/migrations/0002_migrate_old_user.py
  django_project/base_user/migrations/__init__.py
  django_project/base_user/models/__init__.py
  django_project/base_user/models/user.py
  django_project/core/settings/contrib.py
  django_project/core/settings/project.py
  django_project/core/settings/test.py
  django_project/core/test/model_factories.py
  django_project/fish/models/fish_collection_record.py
  django_project/roles/admin.py
  django_project/roles/tests/management_command_role_test.py
Labels: in progress

#107 Change user model to extend user
  deployment/Makefile
  django_project/base/management/__init__.py
  django_project/base/management/commands/__init__.py
  django_project/base/management/commands/migrate_old_profile_data.py
  django_project/base/migrations/0002_profile.py
  django_project/base/models/__init__.py
  django_project/base/models/profile.py
  django_project/base/test/model_factories.py
  django_project/base/test/test_profile.py
  django_project/base_user/migrations/0001_initial.py
  django_project/base_user/migrations/0002_migrate_old_user.py
  django_project/base_user/models/__init__.py
  django_project/base_user/models/user.py
  django_project/core/settings/project.py
  django_project/core/settings/test.py
  django_project/core/test/model_factories.py
  django_project/fish/models/fish_collection_record.py
  django_project/roles/admin.py
  django_project/roles/static/css/role-admin-form.css
  django_project/roles/static/js/role-admin-form.js
  django_project/roles/tests/management_command_role_test.py
Labels: in progress

#109 Api view tests
  deployment/docker/REQUIREMENTS.txt
  django_project/base/tests/__init__.py
  django_project/base/tests/model_factories.py
  django_project/base/tests/test_models.py
  django_project/base/tests/test_profile.py
  django_project/core/tests/__init__.py
  django_project/core/tests/model_factories.py
  django_project/fish/tests/__init__.py
  django_project/fish/tests/model_factories.py
  django_project/fish/tests/test_api_views.py
  django_project/fish/tests/test_models.py
Labels: in progress

#110 Add location site API
  django_project/base/api_views/__init__.py
  django_project/base/api_views/location_site.py
  django_project/base/serializers/__init__.py
  django_project/base/serializers/location_site_detail_serializer.py
  django_project/base/serializers/location_site_serializer.py
  django_project/base/serializers/location_type_serializer.py
  django_project/base/tests/test_api_views.py
  django_project/base/urls.py
  django_project/fish/models/fish_collection_record.py
  django_project/fish/serializers/fish_collection_serializer.py
Labels: in progress

#108 Integrate pygbif and iucn api
  .gitignore
  .travis.yml
  deployment/docker-compose.yml
  deployment/docker/REQUIREMENTS.txt
  django_project/base/celery.py
  django_project/base/management/commands/update_fish_collection_record.py
  django_project/base/management/commands/update_taxa.py
  django_project/base/tasks/__init__.py
  django_project/base/tasks/update_fish_collection_record.py
  django_project/base/utils/__init__.py
  django_project/base/utils/gbif.py
  django_project/base/utils/iucn.py
  django_project/core/settings/celery_settings.py
  django_project/core/settings/contrib.py
  django_project/fish/admin.py
  django_project/fish/migrations/0007_auto_20180317_1052.py
  django_project/fish/migrations/0008_auto_20180320_0756.py
  django_project/fish/migrations/0009_auto_20180320_0837.py
  django_project/fish/models/fish_collection_record.py
  django_project/fish/models/iucn_status.py
  django_project/fish/models/taxon.py
  django_project/fish/serializers/taxon_serializer.py
  django_project/fish/tests/model_factories.py
  django_project/fish/tests/test_models.py
Labels: in progress, needsreview

#99 Landing page
  django_project/base/static/css/landing_page.css
  django_project/base/static/css/map.css
  django_project/base/static/img/algae-icon.png
  django_project/base/static/img/crab-icon.png
  django_project/base/static/img/kartoza-icon.png
  django_project/base/static/img/shark-icon.svg
  django_project/base/static/img/underwater.jpg
  django_project/base/static/js/app.js
  django_project/base/static/js/collections/fish.js
  django_project/base/static/js/models/fish.js
  django_project/base/static/js/shared.js
  django_project/base/static/js/views/olmap.js
  django_project/base/static/js/views/side_panel.js
  django_project/base/templates/landing_page.html
  django_project/base/templates/map.html
  django_project/base/urls.py
  django_project/base/views/landing_page.py
  django_project/core/base_static/css/base.css
  django_project/core/base_static/libs/requirejs-2.3.5/require.js
  django_project/core/base_static/libs/underscore-1.8.3/underscore-min.js
  django_project/core/base_static/libs/underscore-1.8.3/underscore-min.map
  django_project/core/base_templates/main_base.html
  django_project/fish/migrations/0007_auto_20180315_1045.py
Labels: in progress

#111 Fix migration
  django_project/fish/migrations/0010_merge_20180327_0903.py
Labels: in progress
